# model: gemini/gemini-2.0-flash
# model: gemini/gemini-2.0-flash-lite-preview-02-05
# model: gemini/gemini-2.0-flash-thinking-exp
model: gemini/gemini-2.0-pro-exp-02-05
dark-mode: true
# gitignore: false
show-model-warnings: false


