output_dir: "./sessions"
nlp_model: "gemini-2.0-flash-thinking-exp-1219"
code_model: "gemini-2.0-flash-thinking-exp-1219"
system_context: "src/geometor/seer/system_instructions.md"
task_context: "first-six/task_context.md"
